### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_OBJC_CLASS_$_TWTRTwitter"

### ISSUE THREAD

**Issue by grafosecondo** [GoldenOwlAsia/react-native-twitter-signin#133]
I can't build on XCode10, with manually installed libraries. I keep getting the following error

`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TWTRTwitter", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in libRNTwitterSignIn.a(RNTwitterSignIn.o)
     (maybe you meant: _OBJC_CLASS_$_TWTRTwitterAPIConfiguration, _OBJC_CLASS_$_TWTRTwitterText , _OBJC_CLASS_$_TWTRTwitterUploadServiceConfig , _OBJC_CLASS_$_TWTRTwitterTextEntity , _OBJC_CLASS_$_TWTRTwitterAPIServiceConfig , _OBJC_CLASS_$_TWTRTwitterCardsServiceConfig )
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

These are my linked libraries

<img width="652" alt="immagine" src="https://user-images.githubusercontent.com/16417944/59655278-0e27ef00-919a-11e9-8100-6259862a99f9.png">

And I have verified $(inherited) under Build Settings.
The library is sucessfully linked as well.

Please help.

**Comment by grafosecondo** [comment]
sorry, anyone?

**Comment by grafosecondo** [comment]
Tryed compiling with pods, I basically got stuck at the same point

`ld: warning: directory not found for option '-L/Users/***/Library/Developer/Xcode/DerivedData/TVTips-cibylmqvkhjmvqazcguysctwlvco/Build/Products/Debug-iphonesimulator/React'
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TWTRTwitter", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in libreact-native-twitter-signin.a(RNTwitterSignIn.o)
     (maybe you meant: _OBJC_CLASS_$_TWTRTwitterText, _OBJC_CLASS_$_TWTRTwitterAPIServiceConfig , _OBJC_CLASS_$_TWTRTwitterUploadServiceConfig , _OBJC_CLASS_$_TWTRTwitterCardsServiceConfig , _OBJC_CLASS_$_TWTRTwitterAPIConfiguration , _OBJC_CLASS_$_TWTRTwitterTextEntity )
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

help ...

**Comment by punksta** [comment]
I am having the similar issue
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TWTRAPIClient", referenced from:
      objc-class-ref in RNTwitterSignIn.o
  "_OBJC_CLASS_$_TWTRTwitter", referenced from:
      objc-class-ref in RNTwitterSignIn.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by punksta** [comment]
@grafosecondo HI, did you find solution?

**Comment by cyrsis** [comment]
Same Error, interesting, but

works on old xcode 11.3(11C29)

Do not work on the new one

new one 11.3.1(11C504)

**Comment by yash-atreya** [comment]
Any updates on this issue??

I am getting the same error

**Comment by SmartArray** [comment]
TwitterKit library does not include the framework for i386 (release mode).

You have two choices:

1. Run your Build on a **physical** device
2. Set the Build Configuration to **Debug**:

<img width="896" alt="Xcode Build Configuration" src="https://user-images.githubusercontent.com/934592/83347049-4a5c4d00-a322-11ea-878c-e9cfe6ed0dea.png">
